KERNEL_CCFLAGS=-Wall -c -ffreestanding -fno-pie -g -std=gnu99 -Wreturn-type -Wno-write-strings -Wno-unused-variable -Wno-address -Wno-comments
KERNEL_CPPFLAGS=-Wall -c -ffreestanding -fno-pie -g -std=c++11 -Wreturn-type -Wno-write-strings 
#ISOGEN=genisoimage
ISOGEN=mkisofs

# These settings select the native compiler,
# which is likely to work on native linux-x86.
#
# CC=gcc -m32
# LD=ld -melf_i386
# AR=ar
# OBJCOPY=objcopy

# If you are compiling from another platform,
# then use the script build-cross-compiler.sh
# add cross/bin to your path, and uncomment these lines:
CC=i686-elf-gcc
LD=i686-elf-ld
AR=i686-elf-ar
OBJCOPY=i686-elf-objcopy
