KERNEL_CCFLAGS=-m32 -Wall -c -ffreestanding -nostdlib -nodefaultlibs -fno-pie -g -std=c11
KENREL_CPPFLAGS=-m32 -Wall -c -std=c++17 -ffreestanding -nostdlib -nodefaultlibs -fno-pie -fno-builtin -fno-exceptions -fno-leading-underscore -Wno-write-strings -fpermissive
#ISOGEN=genisoimage
ISOGEN=mkisofs

# These settings select the native compiler,
# which is likely to work on native Linux-x86.
# If you are using Ubuntu on WSL to build it, you likely need a 
# cross compiler because the architecture of WSL is not Linux-x86
# If you are using WSL2 you can use the native compiler
#
# NOTE: These settings are for my configuration. I have i686 elf binutils but not gcc. So i will use gcc provided with my distro
CC=gcc -m32
LD=i686-elf-ld -melf_i386
AR=i686-elf-ar
OBJCOPY=i686-elf-objcopy
CPP=gcc -m32

# If you are compiling from another platform,
# then use the script build-crosscompiler.sh
# add cross/bin to your path, and uncomment these lines:
# CC=i686-elf-gcc
# CPP=i686-elf-gcc
# LD=i686-elf-ld
# AR=i686-elf-ar
# OBJCOPY=i686-elf-objcopy
