KERNEL_CCFLAGS=-w -c -ffreestanding -nostdlib -nodefaultlibs -fno-pie -g -std=gnu99
KENREL_CPPFLAGS=-m32 -w -c -ffreestanding -nostdlib -nodefaultlibs -fno-pie -fno-builtin -fno-rtti -fno-exceptions -fno-leading-underscore -Wno-write-strings -fpermissive -g -std=c++11
#ISOGEN=genisoimage
ISOGEN=mkisofs

# These settings select the native compiler,
# which is likely to work on native linux-x86.
# If you are using Ubuntu on WSL to build it, you likely need a 
# cross compiler because the architecture of WSL is not linux-x86
#
# CC=gcc -m32
# LD=ld -melf_i386
# AR=ar
# OBJCOPY=objcopy

# If you are compiling from another platform,
# then use the script build-cross-compiler.sh
# add cross/bin to your path, and uncomment these lines:
CC=i686-elf-gcc
CPP=gcc
LD=i686-elf-ld
AR=i686-elf-ar
OBJCOPY=i686-elf-objcopy
