all: copy

copy:
	@cp ../usr/kevin.txt ../image/usr/share/
	@cp sys/sys.json ../image/sys/reg.json
	@cp etc/sudoers ../image/etc/sudoers
	@cp etc/cash.config ../image/etc/cash.config
	@cp etc/passwd ../image/etc/passwd
	@cp etc/sysinfo.b86 ../image/etc/sysinfo.b86
	@cp etc/sysfile ../image/etc/sysfile
	@cp sys/sysenv.env ../image/etc/sysenv.env
