KERNEL_CCFLAGS=-m32 -w -c -ffreestanding -nostdlib -nodefaultlibs -fno-pie -g -std=gnu11
KENREL_CPPFLAGS=-m32 -w -c -std=c++17 -ffreestanding -nostdlib -nodefaultlibs -fno-pie -fno-builtin -fno-exceptions -fno-leading-underscore -Wno-write-strings -fpermissive

# These settings select the native compiler,
# which is likely to work on native Linux-x86.
# If you are using Ubuntu on WSL to build it, you likely need a
# cross compiler because the architecture of WSL is not Linux-x86
# If you are using WSL2 you can use the native compiler
# Uncomment the lines below if you want to use the
# native compiler that came with your distro
#
# CC=gcc -m32
# LD=ld -melf_i386
# AR=ar
# OBJCOPY=objcopy
# CPP=gcc -m32
# ISOGEN=genisoimage

# If you are compiling from another platform,
# then use the script build-crosscompiler.sh
# and add cross/bin to your path
CC=i686-elf-gcc
CPP=gcc -m32
LD=i686-elf-ld
AR=i686-elf-ar
OBJCOPY=i686-elf-objcopy
ISOGEN=mkisofs