name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fix-term
      run: export TERM=xterm
    - name: fix-toolchain
      run: chmod +x scripts/fix-ci.sh && ./scripts/fix-ci.sh
    - name: make
      run: make
